version: '3.5'

services:
  my-blog_web:
    image: nginx
    ports:
      - 8088:80
    container_name: 'my-blog_web'
    restart: unless-stopped
    volumes:
      - ../docs/.vuepress/dist:/usr/share/nginx/html/blog:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf