version: '3.5'

services:
  my-doc:
    ports:
      - 8000:8080
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: 'my-doc-dev'
    volumes:
      - ../docs:/usr/src/app/docs
